services:
  backend:
    image: ghcr.io/dduneon/stocklens:latest
    container_name: stocklens_backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      FLASK_PORT: "5001"
    networks:
      - service-net

networks:
  service-net:
    external: true
